version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - DB_URI=${DB_URI}
        - DB_USER=${DB_USER}
        - NEO4J_PASSWORD=${NEO4J_PASSWORD}
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - NEXT_PUBLIC_LANGFUSE_SECRET_KEY=${NEXT_PUBLIC_LANGFUSE_SECRET_KEY}
        - NEXT_PUBLIC_LANGFUSE_PUBLIC_KEY=${NEXT_PUBLIC_LANGFUSE_PUBLIC_KEY}
        - NEXT_PUBLIC_LANGFUSE_HOST=${NEXT_PUBLIC_LANGFUSE_HOST}
    ports:
      - '3000:3000'
    environment:
      - DB_URI=${DB_URI}
      - DB_USER=${DB_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEXT_PUBLIC_LANGFUSE_SECRET_KEY=${NEXT_PUBLIC_LANGFUSE_SECRET_KEY}
      - NEXT_PUBLIC_LANGFUSE_PUBLIC_KEY=${NEXT_PUBLIC_LANGFUSE_PUBLIC_KEY}
      - NEXT_PUBLIC_LANGFUSE_HOST=${NEXT_PUBLIC_LANGFUSE_HOST}
